server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 5000
spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mustache:
    prefix: classpath:/templates/
    suffix: .mustache
  servlet:
    multipart:
      max-file-size: 20MB #최대 20MB
      max-request-size: 20MB

  datasource:
    url: jdbc:mysql://localhost:3306/app
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd1234

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always

logging:
  file:
    path: ./images/
  level:
    "[com.example]": ERROR
    "[org.hibernate.type]": TRACE