server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

mybatis:
  mapper-locations: classpath:mappers/**/*.xml

spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mustache:
    prefix: classpath:/templates/
    suffix: .mustache
  servlet:
    multipart:
      max-file-size: 20MB # 최대 20MB
      max-request-size: 20MB

  datasource:
    url: jdbc:mysql://localhost:3306/todoctodoc_back
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: theWell
    password: abcd1234!

  sql:
    init:
      encoding: utf-8
      data-locations:
        - classpath:db/data.sql
      mode: never

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
  output:
    ansi:
      enabled: always

#logging:
#  level:
#    "[com.example]": ERROR
#    "[org.hibernate.type]": TRACE
#  file:
#    path: ./images/
